Repository SQA-Group-1/feel_good_inc, pull requests merged in 2023-11, with the labels that each got.

#51 Add icon and fix text color in android studio
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/feelgoodinc/HomePage.java
  app/src/main/java/com/example/feelgoodinc/fragments/MoodFragment.java
  app/src/main/res/layout/fragment_mood.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: frontend

#39 Resource page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/feelgoodinc/HomePage.java
  app/src/main/java/com/example/feelgoodinc/fragments/PlaceHolderResources.java
  app/src/main/java/com/example/feelgoodinc/fragments/ResourcesFragment.java
  app/src/main/res/drawable/back_arrow.xml
  app/src/main/res/drawable/bank.xml
  app/src/main/res/drawable/books.xml
  app/src/main/res/drawable/button.xml
  app/src/main/res/drawable/directory.xml
  app/src/main/res/drawable/filter.xml
  app/src/main/res/drawable/help_icon.xml
  app/src/main/res/drawable/pair_of_people.xml
  app/src/main/res/drawable/person.xml
  app/src/main/res/drawable/person_waving.xml
  app/src/main/res/drawable/phone.xml
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/drawable/solid_circle.xml
  app/src/main/res/layout/fragment_place_holder_resources.xml
  app/src/main/res/layout/fragment_resources_page.xml
  app/src/main/res/values/styles.xml
Labels: frontend

#57 50 fix initial linter errors
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/android-lint.yml
  .github/workflows/android.yml
  app/build.gradle.kts
  app/src/main/java/com/example/feelgoodinc/fragments/MoodFragment.java
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/fragment_mood.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
  lint.xml
Labels: devops

#72 Refactor: use services instead of classes for `Journal` and `Mood`
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/feelgoodinc/database/MoodDatabaseHelper.java
  app/src/main/java/com/example/feelgoodinc/fragments/MoodFragment.java
  app/src/main/java/com/example/feelgoodinc/services/JournalService.java
  app/src/main/java/com/example/feelgoodinc/services/MoodService.java
  app/src/main/java/com/example/feelgoodinc/services/UserService.java
Labels: backend

#70 Add Resource page child pages
  app/src/main/java/com/example/feelgoodinc/HomePage.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/EducationResources.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/ResourcesFragment.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/SelfHelpStrat.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/SupportGroup.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/emergencyHotline.java
  app/src/main/res/layout/fragment_education_resources.xml
  app/src/main/res/layout/fragment_emergency_hotline.xml
  app/src/main/res/layout/fragment_place_holder_resources.xml
  app/src/main/res/layout/fragment_resources_page.xml
  app/src/main/res/layout/fragment_self_help_strat.xml
  app/src/main/res/layout/fragment_support_group.xml
  app/src/main/res/layout/fragment_user_profile.xml
Labels: frontend

#79 Add calendar firebase connection
  app/src/androidTest/java/com/example/feelgoodinc/CalendarServiceTests.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/feelgoodinc/CalendarUtility.java
  app/src/main/java/com/example/feelgoodinc/HomePage.java
  app/src/main/java/com/example/feelgoodinc/fragments/HomeFragment.java
  app/src/main/java/com/example/feelgoodinc/fragments/MoodFragment.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/EducationResources.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/ResourcesFragment.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/SelfHelpStrat.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/SupportGroup.java
  app/src/main/java/com/example/feelgoodinc/fragments/resourcesFragments/emergencyHotline.java
  app/src/main/java/com/example/feelgoodinc/services/CalendarService.java
  app/src/main/java/com/example/feelgoodinc/services/JournalService.java
  app/src/main/java/com/example/feelgoodinc/services/MoodService.java
  app/src/main/res/layout/fragment_home.xml
Labels: backend
